---

- name: Install basic utils
  yum:
   name: "{{ item }}"
   state: present
  loop:
<<<<<<< Updated upstream
    - vim
    - wget
    - net-tools
    - lsof
    - telnet
    - tmux
    - unzip
    - zsh
    - logrotate
  tags: basic_utils_install

- name: Install EGI CA certificates
  yum:
    name: epel-release
    state: latest
  tags: basic_utils_install

- name: "install pip"
  yum:
    name: python-pip
    state: latest
    enablerepo: epel
=======
   - vim
   - wget
   - net-tools
   - lsof
   - telnet
>>>>>>> Stashed changes
  tags: basic_utils_install
